### ISSUE TITLE
Weird behaviour using `Timex.to_datetime`/`Timex.Timezone.convert` across a DST changeover

### ISSUE THREAD

**Issue by software-opal** [bitwalker/timex#625] opened 2020-11-03 03:21 UTC
#### DST changeover is incorrect
```elixir
# DST fall-backwards happens at 2AM on 1st Nov 2020 in New York
# Before fall-backwards New York is UTC-04:00, afterwards it is UTC-05:00
one_minute_after_new_york_falls_back_to_utc_minus_5 = "2020-11-01T06:01:00-00:00"
local_time_in_new_york = (
    one_minute_after_new_york_falls_back_to_utc_minus_5 
    |> Timex.parse!("{ISO:Extended}") 
    |> Timex.to_datetime("America/New_York")
)
assert local_time_in_new_york |> Timex.format!("{ISO:Extended}") == "2020-11-01T01:01:00-05:00"
# "2020-11-01T02:01:00-04:00" != "2020-11-01T01:01:00-05:00"
#              ^        ^                     ^        ^
```

#### Incorrect handling of DateTimes with timezones
```elixir
# DST fall-backwards happens at 2AM on 1st Nov 2020 in New York.
# Before fall-backwards New York is UTC-04:00, afterwards it is UTC-05:00
input_new_york_time = "2020-11-01T00:00:00-04:00"
weird_new_york_time = (
    input_new_york_time 
    |> Timex.parse!("{ISO:Extended}") 
    |> Timex.to_datetime("America/New_York")
)
assert weird_new_york_time |> Timex.format!("{ISO:Extended}") == input_new_york_time
# "2020-10-31T23:00:00-05:00" != "2020-11-01T00:00:00-04:00"
#        ^ ^^ ^^        ^               ^ ^^ ^^        ^
```

Note that whilst `Timex.to_datetime` is used in the examples, the same issues are apparent when using `Timex.Timezone.convert` instead

### Description of issue

```console
$ mix deps | grep -E 'timex|tzdata'
* tzdata 1.0.3 (Hex package) (mix)
  locked at 1.0.3 (tzdata) a6e1ee70
* timex 3.6.2 (Hex package) (mix)
  locked at 3.6.2 (timex) 26030b46
```

I believe that there is a bug in the way DST is handled somewhere in the `to_datetime/2` code. I've compared the results of moving a UTC datetime to the New York timezone between Elixir(Timex) and Python(datetime) and found this:

| UTC                                        | New York(according to Python) | New York(according to Elixir) | Correct? |
|--------------------------------------------|-------------------------------|-------------------------------|----------|
| `2020-11-01T05:00:00+00:00` (before changeover) | `2020-11-01T01:01:00-04:00`   | `2020-11-01 01:00:00-04:00`   | Yep      |
| `2020-11-01T05:59:00+00:00` (before changeover) | `2020-11-01T01:59:00-04:00`   | `2020-11-01 01:59:00-04:00`   | Yep      |
| `2020-11-01T06:01:00+00:00` (after changeover)  | `2020-11-01T01:01:00-05:00`   | `2020-11-01 02:01:00-04:00`   | No       |
| `2020-11-01T06:59:00+00:00` (after changeover)  | `2020-11-01T01:59:00-05:00`   | `2020-11-01 02:59:00-04:00`   | No       |
| `2020-11-01T07:01:00+00:00` (after changeover)  | `2020-11-01T02:01:00-05:00`   | `2020-11-01 02:01:00-05:00`   | Yep      |

The Python versions are what I would expect having done [some research into the change over in New York](https://www.timeanddate.com/time/change/usa/new-york). New York falls back at 2AM, meaning 01:59AM before changeover is `UTC-04:00`, and 2 minutes later the time is 01:01AM `UTC-05:00`. However the Timex library doesn't appear to do this correctly, instead falling back at 3AM.

There are also some weird interactions with non-UTC date-times, converting `2020-11-01T00:00:00-04:00` to New York time(as noted in the steps to reproduce) should return the same timezone(as New York hasn't fallen backwards yet) however when converting it to New York time it uses `UTC-05:00` rather than `UTC-04:00`. 

#### Python
```python
import zoneinfo, datetime
print(datetime.datetime.fromisoformat("2020-11-01T05:59:00+00:00").astimezone(ZoneInfo('America/New_York')).isoformat())
# Prints 2020-11-01T01:59:00-04:00
print(datetime.datetime.fromisoformat("2020-11-01T06:01:00+00:00").astimezone(ZoneInfo('America/New_York')).isoformat())
# Prints 2020-11-01T01:01:00-05:00
```

### Elixir

```elixir

"2020-11-01T05:59:00+00:00" |> Timex.parse!("{ISO:Extended}") |> Timex.to_datetime("America/New_York") |> Timex.format!("{ISO:Extended}") |> IO.puts()
# Prints 2020-11-01T01:59:00-04:00
"2020-11-01T06:01:00+00:00" |> Timex.parse!("{ISO:Extended}") |> Timex.to_datetime("America/New_York") |> Timex.format!("{ISO:Extended}") |> IO.puts()
# Prints 2020-11-01T02:01:00-04:00
```

**Comment by software-opal** [comment] 2020-11-03 04:17
The intermediate fix for the 2nd issue(Incorrect handling of DateTimes with timezones) is to first convert the DateTime to UTC.

Old Code:
```elixir
"2020-11-01T00:00:00-04:00"
    |> Timex.parse!("{ISO:Extended}") 
    |> Timex.to_datetime("America/New_York")
    |> Timex.format!("{ISO:Extended}") 
    |> IO.puts()
# Prints 2020-10-31T23:00:00-05:00
```

New Code:
```elixir
"2020-11-01T00:00:00-04:00"
    |> Timex.parse!("{ISO:Extended}") 
    |> Timex.to_datetime("UTC")
    |> Timex.to_datetime("America/New_York")
    |> Timex.format!("{ISO:Extended}") 
    |> IO.puts()
# Prints 2020-11-01T00:00:00-04:00
```

**Comment by DunyaKokoschka** [comment] 2021-03-15 19:09
I have seen this problem as well.

The conversion seems to be sensitive to the current time as well. For example it will work correctly at some points in time and not other points in time (???)

I used libfaketime in order to change the current time.

```
DYLD_FORCE_FLAT_NAMESPACE=1 DYLD_INSERT_LIBRARIES=/Users/dunya/work/libfaketime/src/libfaketime.1.dylib FAKETIME="@2021-03-14 02:19:56"
```

```
iex(1)> Timex.Timezone.convert(DateTime.from_naive!(~N[2021-03-14 02:19:56], "Etc/UTC"), Timex.Timezone.get("America/Los_Angeles"))
{:error,
 {:invalid_timezone,
  {:error,
   {:invalid_timezone,
    {:error,
     {:could_not_resolve_timezone, "America/Los_Angeles", 63782907616, :wall}}}}}}
```

and if you run that without faketime

```
iex(1)>  Timex.Timezone.convert(DateTime.from_naive!(~N[2021-03-14 02:19:56], "Etc/UTC"),Timex.Timezone.get("America/Los_Angeles"))
#DateTime<2021-03-13 18:19:56-08:00 PST America/Los_Angeles>
```

**Comment by bitwalker** [comment] 2021-03-18 00:22
Duplicate of #555

**Closed** 2021-03-18 00:50 UTC
