### ISSUE TITLE
Timex.timezone/2 error: could_not_resolve_timezone

### ISSUE THREAD

**Issue by exAspArk** [bitwalker/timex#587] opened 2020-03-09 14:07 UTC
### Steps to reproduce

It seems that `Timex.timezone/2`  turned into a pumpkin between 2AM - 3AM UTC on March 8, 2020 (DST starts in `America/New_York` time zone).

It was throwing this error for an hour, then suddenly stopped:

```ex
iex> Timex.timezone("America/New_York", DateTime.utc_now())
{:error, {:could_not_resolve_timezone, "America/New_York", 63750852048, :wall}}
```

**Comment by mohammedgad** [comment] 2021-03-14 03:28
That is still happening in a very random way, any Insights on why this is happening or how to reproduce it?

**Comment by jamiesunderland** [comment] 2021-03-14 20:28
@mohammedgad this happened to us in production yesterday and caused a huge fiasco. Timex does not  handle the first hour of DST changeover.

**Comment by mohammedgad** [comment] 2021-03-14 20:35
@jamiesunderland that makes sense, I also encountered this on production yesterday, this needs to be fixed.

**Comment by bitwalker** [comment] 2021-03-14 21:30
I'll take a look this evening, but this is likely due to the `timezone/2` function using wall time as a convenience to avoid returning ambiguous results. Using that function to create DateTimes is not it's intended purpose though, it is meant to be used to obtain a timezone record from a known good time, not to get a timezone for any random DateTime, but it probably should have been deprecated a long time ago due to the way it's being used.

**Comment by mohammedgad** [comment] 2021-03-14 21:55
Hi @bitwalker Thank you for looking this up.
Just for the record, I encountered this error while using `Timex.Timezone.get("America/New_York")` I hope that helps more to identify the issue.

**Comment by jamiesunderland** [comment] 2021-03-14 22:09
Not sure if it's much help either but I had this failing as in our tests between 6-7 pm PST.

```
== Compilation error in file test/cheqout/labor/contexts/shifts_context_test.exs ==
** (FunctionClauseError) no function clause matching in Timex.Timezone.total_offset/1    
    
    The following arguments were given to Timex.Timezone.total_offset/1:
    
        # 1
        {:error, {:invalid_timezone, {:error, {:could_not_resolve_timezone, "America/Los_Angeles", 63782909257, :wall}}}}
    
    Attempted function clauses (showing 1 out of 1):
    
        def total_offset(%Timex.TimezoneInfo{offset_std: std, offset_utc: utc})
```

**Comment by bitwalker** [comment] 2021-03-18 01:39
This has been fixed locally, but I haven't yet pushed the changes. Should be up shortly

**Comment by bitwalker** [comment] 2021-03-18 01:39
Duplicate of #555

**Closed by bitwalker** 2021-03-18 01:39 UTC
