### ISSUE TITLE
Timezone.local/1 crashes during DST fallback

### ISSUE THREAD

**Issue by keenajohn** [bitwalker/timex#631] opened 2020-12-22 15:30 UTC
### Steps to reproduce

Timex.local(Timex.to_datetime({{2020,10,25}, {2,30,0}}, :utc))

### Description of issue

** (KeyError) key :full_name not found in: #<Ambiguous(#<TimezoneInfo(Europe/Berlin - CEST (+02:00:00))> ~ #<TimezoneInfo(Europe/Berlin - CET (+01:00:00))>)>
    (timex) lib/timex.ex:82: Timex.local/1

local/1 should handle the case where an AmiguousTimeZone is returned. local/0 already handles this case.

**Comment by bitwalker** [comment] 2021-03-18 00:22
Duplicate of #555

**Closed by bitwalker** 2021-03-18 00:22 UTC
