### ISSUE TITLE
CaseClauseError error while shifting date_time with timezone

### ISSUE THREAD

**Issue by mkorszun** [bitwalker/timex#472] opened 2018-10-09 12:51 UTC
### Steps to reproduce

- API function called: `Timex.shift/2`
- Arguments provided: `[Timex.to_datetime(~N[2011-11-21 10:57:52]) |> Timex.Timezone.convert("America/Catamarca"), [weeks: -1049]]`
- version: `3.4.1`
### Description of issue

- Expected results

Shifted date

- Actual results

```
Timex.shift(Timex.to_datetime(~N[2011-11-21 10:57:52]) |> Timex.Timezone.convert("America/Catamarca"), [weeks: -1049])
** (CaseClauseError) no case clause matching: [%{from: %{standard: 62835174000, utc: 62835184800, wall: 62835174000}, std_off: 0, until: %{standard: 62855136000, utc: 62855146800, wall: 62855136000}, utc_off: -10800, zone_abbr: "-03"}, %{from: %{standard: 62835170400, utc: 62835184800, wall: 62835170400}, std_off: 0, until: %{standard: 62855136000, utc: 62855150400, wall: 62855136000}, utc_off: -14400, zone_abbr: "-04"}, %{from: %{standard: 62835177600, utc: 62835188400, wall: 62835177600}, std_off: 0, until: %{standard: 62855136000, utc: 62855146800, wall: 62855136000}, utc_off: -10800, zone_abbr: "-03"}]
    (timex) lib/timezone/timezone.ex:313: Timex.Timezone.resolve/3
    (timex) lib/timezone/timezone.ex:337: Timex.Timezone.resolve/3
    (timex) lib/datetime/datetime.ex:402: Timex.Protocol.DateTime.shift_by/3
    (timex) lib/datetime/datetime.ex:251: Timex.Protocol.DateTime.apply_shifts/2
```

- Similar logic with [`moment.js`](https://momentjs.com)

~~~
$ npm install moment-timezone
$ node

> var moment = require('moment-timezone');
> moment.tz("2011-11-21 10:57:52", "America/Catamarca").subtract(1049, 'week').toString()
'Mon Oct 14 1991 10:57:52 GMT-0400'
~~~

**Comment by vorce** [comment] 2018-10-10 10:54
This seems tied to the tzdata version, at least I could not reproduce it with tzdata 0.5.17. Changing to tzdata 0.5.19 will trigger this defect.

**Comment by bitwalker** [comment] 2018-10-18 20:47
Interesting, there are 3 time zones possible (based on wall time) for that date/time. 

@ckhrysze Thoughts on this one?

**Comment by bitwalker** [comment] 2018-10-19 01:47
Fixed in master

**Closed by bitwalker** 2018-10-19 01:47 UTC
Labels: bug, level:intermediate
