### ISSUE TITLE
could_not_resolve_timezone for America/Santiago September 8th 2019

### ISSUE THREAD

**Issue by silva96** [bitwalker/timex#555] opened 2019-08-26 18:48 UTC
I updated to 3.6.1 hoping the commit (https://github.com/bitwalker/timex/commit/ab03f307fd2204a869183a9d957967bdf2eef8b1) that fixes #514 would solve the issue, but it doesn't.

What I need to do is have the DateTime for the very beginning of the day of the 8th of september in America/Santiago timezone. This day, there is a change from CLT to CLST (summer time, daylight savings ends exactly at 23.59.59.999999 and time goes to 01 am instead of 00 am.)

Having the following example, I would expect to have valid dates in both cases (07-september-2019 and 08-september-2019, but the latter fails with `:could_not_resolve_timezone`

```elixir
ok_date = "2019-09-07"
Timex.parse!(ok_date, "%Y-%m-%d", :strftime) |> Timex.to_datetime("America/Santiago")

#DateTime<2019-09-07 00:00:00-04:00 -04 America/Santiago>

not_ok_date = "2019-09-08"
Timex.parse!(not_ok_date, "%Y-%m-%d", :strftime) |> Timex.to_datetime("America/Santiago")

{:error,
 {:could_not_resolve_timezone,
  "America/Santiago", 63735120000,
  :wall}}
```

In ruby/rails works perfectly fine.

```ruby
ok_date = "2019-09-07"
ActiveSupport::TimeZone.new('America/Santiago').parse(ok_date)
=> Sat, 07 Sep 2019 00:00:00 -04 -04:00

not_ok_date = "2019-09-08"
ActiveSupport::TimeZone.new('America/Santiago').parse(not_ok_date)
=> Sun, 08 Sep 2019 01:00:00 -03 -03:00
```

More over, substracting minutes from the beginning of conflicting day gives totally wrong date:

```elixir
ok_date = "2019-09-07 00:00:00"        
Timex.parse!(ok_date, "%Y-%m-%d %H:%M:%M", :strftime)  
|> Timex.to_datetime("America/Santiago") 
|> Timex.shift(minutes: -10)

#DateTime<2019-09-06 23:50:00-04:00 -04 America/Santiago>

not_ok_date = "2019-09-08 01:00:00" # the day begins at 1 am, thats OK

# going 10 minutes before goes 50 mintues in the future.

Timex.parse!(not_ok_date, "%Y-%m-%d %H:%M:%M", :strftime)  
|> Timex.to_datetime("America/Santiago") 
|> Timex.shift(minutes: -10)

#DateTime<2019-09-08 01:50:00-03:00 -03 America/Santiago>

# but going forward is fine

Timex.parse!(not_ok_date, "%Y-%m-%d %H:%M:%M", :strftime)  
|> Timex.to_datetime("America/Santiago") 
|> Timex.shift(minutes: 10)

#DateTime<2019-09-08 01:10:00-03:00 -03 America/Santiago>
```

**Comment by bbassett** [comment] 2019-09-07 23:15
I have just run into this issue as well, for the duration of exactly one, the `Pacific/Easter` timezone when called with `Timex.Timezone.get/1` was broken. 

you can replicate it with the following:
```
iex(24)> Timex.Timezone.get("Pacific/Easter", {{2019, 9, 7}, {22, 10, 0}})
{:error, {:could_not_resolve_timezone, "Pacific/Easter", 63735113400, :wall}}
```
we had an error for exactly one hour, which led  me down this rabbit hole, and as it has happened with at least two time zones at different times, i'm sure there's an underlying bug.

**Comment by chungwong** [comment] 2019-10-04 04:33
I am experiencing a similar issue.
any datetime between `02:00:00` to `02:59:59` will throw the same error.
```
Timex.parse!("2019-10-06T02:00:00.765Z", "{ISO:Extended:Z}") |> Timex.local
{:error, {:could_not_resolve_timezone, "Australia/Sydney", 63737546400, :wall}}
```

**Comment by jamiesunderland** [comment] 2021-03-14 03:36
We hit this bug in production today and had a lot of issues for 1 hour. I really hope this gets fixed eventually.

**Comment by silva96** [comment] 2021-03-17 20:17
Each year a new victim :D

**Comment by bbassett** [comment] 2021-03-17 22:21
Just to chime back in on this. There actually isn't a bug. The problem occurs when you try to resolve a time that actually doesn't exist in a specific timezone. I remember digging in _deep_.

the time doesn't exist because during daylight savings times, different regions skip hours, so the time inside of that hour for that TZ is invalid. 

bottom line is: you should confirm that when you resolve a time it returns a struct, rather than an error tuple.

i'd recommend @bitwalker  closes this issue

**Comment by bitwalker** [comment] 2021-03-17 22:26
There is a better solution to helping this actually, and I’m finishing up the changes along with a variety of other fixes; should be pushed by EOW

**Comment by chungwong** [comment] 2021-03-17 22:38
> Just to chime back in on this. There actually isn't a bug. The problem occurs when you try to resolve a time that actually doesn't exist in a specific timezone. I remember digging in _deep_.
> 
> the time doesn't exist because during daylight savings times, different regions skip hours, so the time inside of that hour for that TZ is invalid.
> 
> bottom line is: you should confirm that when you resolve a time it returns a struct, rather than an error tuple.
> 
> i'd recommend @bitwalker closes this issue

In my opinion it is a bug and a serious one too.
When I simply want a datetime and all I get during that 1 hour of timezone change, is an error. Even though I catch the error tuple, then what I do with it. There is no way for me to get a timestamp anyway.

**Comment by DunyaKokoschka** [comment] 2021-03-18 17:36
> Just to chime back in on this. There actually isn't a bug. The problem occurs when you try to resolve a time that actually doesn't exist in a specific timezone. I remember digging in _deep_.
> 
> the time doesn't exist because during daylight savings times, different regions skip hours, so the time inside of that hour for that TZ is invalid.
> 
> bottom line is: you should confirm that when you resolve a time it returns a struct, rather than an error tuple.
> 
> i'd recommend @bitwalker closes this issue

There is actually a bug. You can check here for instructions on how to reproduce it: https://github.com/bitwalker/timex/issues/625#issuecomment-799680070

**Comment by bitwalker** [comment] 2021-03-18 18:33
This is fixed in 3.7

**Closed by bitwalker** 2021-03-18 18:33 UTC

**Comment by jamiesunderland** [comment] 2021-03-18 19:38
@bitwalker thank you so much for the quick turn around here!

**Comment by nonrational** [comment] 2021-03-18 19:40
Thanks for looking into this @bitwalker. I'm seeing the issue as described in https://github.com/bitwalker/timex/issues/587 with 3.7.1 

```elixir
{:ok, before_dst, _} = DateTime.from_iso8601("2021-03-14T01:00:00Z")
%Timex.TimezoneInfo{} = Timex.timezone("America/New_York", before_dst)

{:ok, at_dst, _} = DateTime.from_iso8601("2021-03-14T02:00:00Z")
{:error, {:could_not_resolve_timezone, "America/New_York", 63782906400, :wall}} = Timex.timezone("America/New_York", at_dst)
```

**Comment by nonrational** [comment] 2021-03-19 14:50
I'm using `Timex.timezone/2` to look up the full `%Timex.TimezoneInfo{}` as of a given UTC datetime for a named timezone (e.g. `"America/New_York"` -> `%Timex.TimezoneInfo{abbreviation: "EDT"}`).

Will try with 3.7.2!

**Comment by bitwalker** [comment] 2021-03-19 14:54
As of 3.7.2 you are better off calling ‘Timex.Timezone.get/2` with a NaiveDateTime if you want a TimezoneInfo that reflects the wall clock time in a given zone, give that a shot instead.

**Comment by nonrational** [comment] 2021-03-19 15:04
`Timex.Timezone.get/2` works exactly as expected. Thank you!

**Comment by fSergio101** [comment] 2021-03-29 11:48
Hello guys, I've experienced this issue last Sunday when the DST happened in Spain (Using v3.6.1). Today I've just reproduced it doing the following

- 1. Set computer time to 4:20:00 March 28th (2:10 UTC)
- 2. Run:
```
Timex.Timezone.get("Europe/Madrid", NaiveDateTime.utc_now())
```

then I got 

```

** (FunctionClauseError) no function clause matching in Timex.Timezone.total_offset/1

    The following arguments were given to Timex.Timezone.total_offset/1:

        # 1
        {:error, {:could_not_resolve_timezone, "Europe/Madrid", 63784117369, :wall}}

    Attempted function clauses (showing 1 out of 1):

        def total_offset(%Timex.TimezoneInfo{offset_std: std, offset_utc: utc})

    (timex) lib/timezone/timezone.ex:447: Timex.Timezone.total_offset/1
```
- 3. Update to v3.7.2
- 4. Run:

```
Timex.Timezone.get("Europe/Madrid", NaiveDateTime.utc_now())
```

and I got again the same error:

```

** (FunctionClauseError) no function clause matching in Timex.Timezone.total_offset/1

    The following arguments were given to Timex.Timezone.total_offset/1:

        # 1
        {:error, {:could_not_resolve_timezone, "Europe/Madrid", 63784117369, :wall}}

    Attempted function clauses (showing 1 out of 1):

        def total_offset(%Timex.TimezoneInfo{offset_std: std, offset_utc: utc})

    (timex) lib/timezone/timezone.ex:447: Timex.Timezone.total_offset/1
```

has this issue already been fixed? and it's me missing something??

**Comment by chungwong** [comment] 2021-03-29 12:02
Unfortunately Timex introduced a broken(a serious one) change.

https://github.com/bitwalker/timex/issues/651

**Comment by fSergio101** [comment] 2021-03-29 14:26
Which is te relation between the given example and the breaking change you are pointing? I', using in the example a `NaiveDateTime` that is supposed to be agnostic from timezones. 🤔 So AFAIK there should be no relation. Moreover, this behaviour is just transient and after one hour it backs to the right one.

> Unfortunately Timex introduced a broken(a serious one) change.
> 
> #651
