### ISSUE TITLE
Ensure shifting is consistent for both DateTime and Date/NaiveDateTime

### ISSUE THREAD

**Issue by tmaszk** [bitwalker/timex#360] opened 2017-09-02 13:26 UTC
### Steps to reproduce
```
iex(1)> date = ~D[2017-01-31]
~D[2017-01-31]
iex(2)> date |> Timex.shift(months: 1)
~D[2017-02-28]
iex(3)> date |> Timex.to_datetime |> Timex.shift(months: 1)
#DateTime<2017-03-03 00:00:00Z>
```
The last result should be: `#DateTime<2017-02-28 00:00:00Z>`

### Description of issue

- `shift()` should return the same result regardless of date format
- I prefer the way Timex implements the NavieDate shift.  When shifting to another month that is shorter than the original month, the shifted date should be adjusted to the end of the month
- The difference between the two shift behaviors is properly documented in:
https://github.com/bitwalker/timex/blob/master/lib/datetime/datetime.ex#L326-L327
https://github.com/bitwalker/timex/blob/master/lib/datetime/naivedatetime.ex#L257-L258
- It looks like the change to `shift` for DateTime was introduced while fixing https://github.com/bitwalker/timex/issues/313

Would you be willing to make these consistent?  
I can submit a pull request for the change.

**Comment by bitwalker** [comment] 2017-09-26 20:21
Making these consistent would be a welcome change! I would prefer we follow the implementation in `datetime.ex`, because it addresses bugs and a large amount of discussion around this topic that has already occurred. The implementation in `naivedatetime.ex` is from my original rewrite over a year ago, and looks like it never got updated like the datetime implementation did.

If you submit a PR, I'll be happy to get it reviewed and merged ASAP :)

**Comment by bitwalker** [comment] 2017-09-27 02:32
So for reference, here are the issues/PRs which have previously dealt with this:

#324 
#281
#271

281 has the most discussion. One of the things that has complicated this is that most users of Timex expect that shifting and diffing are mirrored, i.e. if you shift and then diff, the diff should reflect the shift. If you adjust the shift as you have illustrated, then it breaks diffs, which has confused quite a few people, and is one of the reasons why 1.) there has been so much back and forth on it implementation-wise, and 2.) why I finally went with the "shifting should match diffing" solution. Given your example, doing `Timex.diff(jan1, jan1plus1m, :months)` would return `0` if the shift stops at the end of February, which obviously seems bizarre given that you just shifted it by a month. If anything, I would prefer to deprecate shifting by months due to it's ambiguity, but given that a number of people appear to use it, that's not likely to happen. The issue is simply that it's not a well-defined unit to shift by, and what it means to shift by a month is not well specified because of this; the intuitive result for shifting produces unintuitive results when diffing, so there is no perfect solution.

Changing the diff algorithm to use your implementation both complicates the diff logic, and results in shifts no longer being idempotent (i.e. shifting a date/time, then shifting it back using the diff should produce the original date/time, but won't in some edge cases, such as shifting from any 31 day month to a non-31 day month, on the 31st).

I'm definitely interested to hear if you have any ideas though! If we can preserve both intuition and idempotency, I'm very open to changing the algorithm, but we are where we are today due to the inability to unify them, so rather than change direction yet again, I would prefer to maintain the course we've chosen unless there is good reason to do otherwise.

**Comment by tmaszk** [comment] 2017-09-27 11:28
Thanks for the links and background.  The issue is more complicated than I realized.  I'll research some more and see if I can come up with something that satisfies both shifting and diffing.

**Closed** 2018-05-08 21:56 UTC
Labels: feature/enhancement
