### ISSUE TITLE
Problems with timezone conversions around the end of daylight saving time

### ISSUE THREAD

**Issue by mkummer** [bitwalker/timex#142] opened 2016-03-28 13:38 UTC
### Steps to reproduce

I just stepped across several difficulties converting timestamps from my local time zone to UTC and back, when they are occurring around the end of daylight saving time (the change occurred Oct 25 2015, 01:00 UTC).
Trying to convert a datetime right after the 'extra' hour when daylight saving time was ending last fall from my local timezone (Zurich) into UTC fails:
```elixir
Interactive Elixir (1.2.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Timex.datetime({ {2015, 10, 25}, {03, 12, 34} }, "Europe/Zurich") |> Timex.Timezone.convert("UTC")
** (FunctionClauseError) no function clause matching in Timex.Timezone.resolve/2
    (timex) lib/timezone/timezone.ex:182: Timex.Timezone.resolve("UTC", {:error, :badarg})
    (timex) lib/timezone/timezone.ex:268: Timex.Timezone.convert/2
```
The hour from 02:00:00–02:59:59 occurs twice in succession, first in the daylight saving time zone, then in the normalized time zone. But any value after 03:00:00 is unique, so this conversion is supposed to work fine.
Even worse, picking a timestamp during this 'duplicated' hour results in an unresponsive iex:
```elixir
iex(1)> Timex.datetime({ {2015, 10, 25}, {02, 12, 34} }, "Europe/Zurich") |> Timex.Timezone.convert("UTC")
[iex freezes with high CPU load, have to break using Ctrl-C]
```
Going the opposite way reveals a different error:
```elixir
iex(1)> Timex.datetime({ {2015, 10, 25}, {00, 12, 34} }, "UTC") |> Timex.Timezone.convert("Europe/Zurich")
#<Ambiguous(#<DateTime(2015-10-25T02:12:34 Europe/Zurich (+02:00:00))> ~ #<DateTime(2015-10-25T01:12:34 Europe/Zurich (+01:00:00))>)>
```
This time in fact is NOT ambiguous; the only correct result is `#<DateTime(2015-10-25T02:12:34 Europe/Zurich (+02:00:00))>`.

`#<DateTime(2015-10-25T01:12:34 Europe/Zurich (+01:00:00))>` actually is not valid, as the +01:00 timezone does not kick in before 02:00 (+01:00)

Last but not least, let's try the conversion UTC-to-local one hour later:
```elixir
iex(2)> Timex.datetime({ {2015, 10, 25}, {01, 12, 34} }, "UTC") |> Timex.Timezone.convert("Europe/Zurich")
** (KeyError) key :millisecond not found
    (timex) lib/timezone/timezone.ex:274: Timex.Timezone.convert/2
```
Now we get yet a different error.
The expected result would be `#<DateTime(2015-10-25T02:12:34 Europe/Zurich (+01:00:00))>`

My Erlang version for completeness:
```sh
Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
```

### Description of issue

- Timezone conversions around the ending of a daylight saving time zone result in several different errors

**Comment by bitwalker** [comment] 2016-03-28 15:37
Interesting that this doesn't occur with some other DST-related tests. I've done some review though, and I think I see where the issue is. I'll update this thread once I have a fix pushed. Thanks for the detailed report!

**Comment by bitwalker** [comment] 2016-03-28 16:45
@mkummer I did find one assumption that is incorrect here:

> This time in fact is NOT ambiguous; the only correct result is `#<DateTime(2015-10-25T02:12:34 Europe/Zurich (+02:00:00))>`.

Actually that time is ambiguous according to the wall clock. Here's what is in the Olson timezone database:

```
iex(12)> :calendar.datetime_to_gregorian_seconds({{2015,10,25},{2,12,34}})
63612958354
iex(13)> Tzdata.periods_for_time "Europe/Zurich", 63612958354, :wall
[%{from: %{standard: 63594813600, utc: 63594810000, wall: 63594817200},
   std_off: 3600,
   until: %{standard: 63612957600, utc: 63612954000, wall: 63612961200},
   utc_off: 3600, zone_abbr: "CEST"},
 %{from: %{standard: 63612957600, utc: 63612954000, wall: 63612957600},
   std_off: 0,
   until: %{standard: 63626263200, utc: 63626259600, wall: 63626263200},
   utc_off: 3600, zone_abbr: "CET"}]
```

As you can see, there is an overlap in wall time between the two zones, which represents how time is perceived locally. As you described, the hour occurs twice, however neither zone can be said to own the time of 2-3 AM, it is technically both, and the ambiguity is regarding *which* 2-3 AM hour you are trying to represent. That is why you get back an AmbiguousDateTime with both possible choices, you have to specify which of the two you actually wanted.

I suspect this may have an effect on some of your other notes, however I have already made one fix, and I'll be reviewing each of them in turn to see if there are other bugs hiding there as well.

**Comment by mkummer** [comment] 2016-03-28 18:06
@bitwalker : first of all many thanks for your quick response!

Regarding my remark about `Timex.datetime({ {2015, 10, 25}, {00, 12, 34} }, "UTC") |> Timex.Timezone.convert("Europe/Zurich")` not being ambiguous: according to my understanding so far, the timestamp in UTC I start with clearly is not ambiguous, and simply converting it to my local timezone shouldn't make it ambiguous either, as at that very point in time only the DST variant of the time zone exists. But obviously you are right if we are talking about wall time, I apologize for being not very precise there.

Still I don't understand why `#<DateTime(2015-10-25T01:12:34 Europe/Zurich (+01:00:00))>` should be considered valid, when the transition to the `+01:00:00` variant occurs only at `02:00:00` – but that's clearly my own problem. You are following the principles of the Olson db here which I'm not trying to question. Obviously I have to do some more research into the common practice regarding dealing with DST transitions. Thanks for pointing that out to me!

**Comment by bitwalker** [comment] 2016-03-28 19:43
@mkummer Just to be clear, I have found some edge cases due to this, so not everything is correct by the Olson database either.

Regarding converting from `2015/10/25 00:12:34 UTC` to `Europe/Zurich` - the timestamp you start with in UTC may be valid/unambiguous in UTC, but according to the timezone database at this exact time in UTC, there are two timezones in effect according to wall time, even though 00 in UTC would correspond to 02 in CEST, and 01 in UTC would correspond to 02 in CET, the date/time `2015/10/25 02:00:00` can represent both, and is thus ambiguous.

The question then becomes, do we allow Timex to automatically resolve the ambiguity for this case since it has the knowledge to say which of the two timezones applies for that hour in UTC? We could, however any operation which further modifies the date/time will no longer have that context, and we can't distinguish which timezone to use when Olson comes back with both again. It seems to me that it would be even more confusing to get back an unambiguous DateTime in the one case, but then, let's say shift it by 5 minutes, and suddenly you get an AmbiguousDateTime back. I would rather return the ambiguous value in both cases, and rely on the consuming code to handle choosing.

Do you have thoughts on that?

As an update, I've addressed the bugs I did find, and pushed a fix. I'll push a new release shortly.

**Closed** 2016-03-28 19:43 UTC
Labels: 2.x, bug, level:advanced

**Comment by mkummer** [comment] 2016-03-28 19:54
Perfect, that's an awesome service, thank you. Your fixes are effective indeed as from what I can tell after a few tests.

Regarding your question, I support your opinion of keeping the ambiguity and letting the application code handling the case; I think this is the more universal approach.

**Comment by bitwalker** [comment] 2016-03-28 20:03
@mkummer Great to hear :)

If you run into any other edge cases, or have any further questions about how Timex handles shifting across timezones, feel free to open an issue anytime. I like having a history of bug reports/discussions to go through, helps other people as much as it helps myself sometimes :)
