### ISSUE TITLE
CaseClauseError while calling `Timex.Timezone.convert`

### ISSUE THREAD

**Issue by mkorszun** [bitwalker/timex#473] opened 2018-10-09 15:04 UTC
### Steps to reproduce

- API function called: `Timex.Timezone.convert`
- Arguments provided: `[Timex.to_datetime(~N[2011-08-11 13:30:31]), "Asia/Gaza"]`
- version: `3.4.1`

### Description of issue

- Expected result - date_time with timezone
- Actual results
~~~
iex(1)> Timex.Timezone.convert(Timex.to_datetime(~N[2011-08-11 13:30:31]), "Asia/Gaza")
** (CaseClauseError) no case clause matching: [%{from: %{standard: 63468835260, utc: 63468828060, wall: 63468838860}, std_off: 3600, until: %{standard: 63481878000, utc: 63481870800, wall: 63481881600}, utc_off: 7200, zone_abbr: "EEST"}, %{from: %{standard: 63479372400, utc: 63479365200, wall: 63479372400}, std_off: 0, until: %{standard: 63484560000, utc: 63484552800, wall: 63484560000}, utc_off: 7200, zone_abbr: "EET"}, %{from: %{standard: 63479376000, utc: 63479368800, wall: 63479376000}, std_off: 0, until: %{standard: 63492595200, utc: 63492588000, wall: 63492595200}, utc_off: 7200, zone_abbr: "EET"}]
    (timex) lib/timezone/timezone.ex:313: Timex.Timezone.resolve/3
    (timex) lib/timezone/timezone.ex:453: Timex.Timezone.convert/2
~~~
- Similar logic with [`moment.js`](https://momentjs.com)

~~~
$ npm install moment-timezone
$ node

> var moment = require('moment-timezone');
> moment.tz("2011-08-11 13:30:31", "Asia/Gaza").toString()
'Thu Aug 11 2011 13:30:31 GMT+0200'
~~~

**Comment by vorce** [comment] 2018-10-10 10:55
This seems tied to the tzdata version, at least I could not reproduce it with tzdata 0.5.17. Changing to tzdata 0.5.19 will trigger this defect.

**Comment by bitwalker** [comment] 2018-10-18 20:48
Same issue as the last one @ckhrysze

**Comment by bitwalker** [comment] 2018-10-19 01:46
I'm closing this with the fix in master, but have noted that additional work needs to be done in order to fully resolve this issue (namely support for more than two selections in ambiguous periods).

**Closed by bitwalker** 2018-10-19 01:46 UTC
Labels: bug, level:intermediate
