### ISSUE TITLE
Probably bug with %W parsing of first day of the year

### ISSUE THREAD

**Issue by nulian** [bitwalker/timex#280] opened 2017-02-16 14:23 UTC
When formatting a date time with %W before the first monday of the new week it should probably return week 0.

Timex.to_date({2017,1,1}) |> Timex.format!("%W", :strftime) == 52

Most other libraries I compared it with return 0 with %W and 52 with %V.

**Comment by nulian** [comment] 2017-02-16 14:50
Found another one the result should be 42.

Timex.to_datetime({{2013,10,21},{10,0,0}}) |> Timex.format!("%W", :strftime) == 43

**Comment by bitwalker** [comment] 2017-02-16 21:42
Yeah looks like `%W` got hooked up to the ISO week number, I'll get that fixed ASAP.

**Comment by bitwalker** [comment] 2017-02-16 22:50
This is fixed in master, I'll release it once you've confirmed in your testing that everything looks good.

**Closed** 2017-02-16 22:50 UTC
Labels: bug

**Comment by nulian** [comment] 2017-02-17 08:43
Yep tnx it shows the correct numbers with the master branch.

**Comment by bitwalker** [comment] 2017-02-17 18:38
I pushed a new release today with the fix. Thanks!
