### ISSUE TITLE
Parsing fails for days of month > 9 for {UNIX} and {ANSIC} 

### ISSUE THREAD

**Issue by rayd** [bitwalker/timex#103] opened 2015-11-22 18:08 UTC
It looks like when trying to parse a date-time string using the built-in `{UNIX}` and `{ANSIC}` formats, double-digit days of the months cause the parse operation to fail.

This works:
```
iex(81)> "Fri Nov 6 22:23:48 UTC 2015" |> Timex.DateFormat.parse("{UNIX}")
{:ok,
 %Timex.DateTime{calendar: :gregorian, day: 6, hour: 22, minute: 23, month: 11,
  ms: 0, second: 48,
  timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min,
   full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2015}}
```
But this doesn't:
```
iex(82)> "Mon Nov 16 22:23:48 UTC 2015" |> Timex.DateFormat.parse("{UNIX}")
{:error, "Expected space but found `6` at line 1, column 10."}
```
(And same thing for the `{ANSIC}` format.)

I'm using Elixir `1.1.1`, Erlang `18.1` and the `1.0.0-rc2` version of Timex on Arch Linux.

**Comment by bitwalker** [comment] 2015-11-23 15:47
@rayd Looking at this now, thanks for reporting! It looks like this one slipped through the cracks :(

**Comment by bitwalker** [comment] 2015-11-23 15:54
Well that is odd, I added a test with your example, and it passes the tests for me. Could you try with master? Perhaps this is something that has been recently fixed but not pushed as a release yet.

**Comment by bitwalker** [comment] 2015-11-23 15:56
Correction! Sorry, I was looking at the formatter tests, not parser. I can reproduce.

**Comment by bitwalker** [comment] 2015-11-23 16:03
Found the problem and pushed a fix to master. I should be pushing a new release sometime today.

**Closed** 2015-11-23 16:03 UTC

**Comment by rayd** [comment] 2015-11-23 17:05
awesome! installed from master and looking good - impressive response time :)
